---
- name: Routers setup
  hosts: servers
  gather_facts: False
  vars:
    input: "{{ lookup('file','{{ filename }}') | from_json }}"

  tasks:
   - name: Get new router name
     set_fact:
       router_name: "{{ input.inventory_hostname }}"

   - name: Set router name
     community.routeros.command:
       commands: /system identity set name={{ router_name }}

   - name: Get interfaces
     set_fact:
       interfaces: "{{ input.interfaces }}"

   - name: Set interface bridge_lo
     community.routeros.command:
       commands:
         - /interface bridge add name="{{ item.name }}"
         - /ip address add address="{{ item.ip_addresses[0].address }}" interface="{{ item.name }}"
     when: item.name == "loopback2"
     with_items: "{{ interfaces }}"
